/* (c) 2019 Confio UO. Licensed under Apache-2.0 */

/* Generated with cbindgen:0.18.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Execute func
 *
 * params is gas u64
 */
void execute(uint64_t gas_limit);

/**
 * Returns a version number of this library as a C string.
 *
 * The string is owned by libmovevm and must not be mutated or destroyed by the caller.
 */
const char *version_str(void);
